apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/dr-platform-devops/crossplane-argocd-reference-implementation'
    targetRevision: main
    path: helm/crossplane-demo
  project: default
  syncPolicy:
    automated: null
